### PR TITLE
usage of php-parser

### PR DESCRIPTION
**Pull request by ichiriac**
first implementation with the php-parser
---
`gulp test` passes without any warning :smile:

### CODE REVIEW

**Comment by felixzapata** [comment]
Hi @ichiriac, I`ve checked your changes with this test:

```javascript
   it('10) Should review that the domain (set as a constant) is ok', function(done) {
    var actual;
    var corrected;
    var expected;
    var options = {
      force: true,
      text_domain: 'TEST',
      create_report_file: true,
      keywords: keywords
    };

    gulp.src(fixtures('correct-domain-constant.php'))
      .pipe(checktextdomain(options))
      .pipe(sassert.first(function(d) {
        //File is correct, should report no errors
        actual = JSON.parse(fs.readFileSync('.correct-domain-constant.json'));
        actual[path.join(__dirname, 'temp/correct-domain-constant.php')].length.should.equal(0);

        //Clean up: Delete report file
        fs.remove('.correct-domain-constant.json');
      }))
      .pipe(sassert.end(done));

  });
```

and with this fixture:

```php
<?php

define( 'TEST', 'my-domain' );

__( 'Hello World', TEST );
_x( 'Post', 'verb', TEST );
_e( 'Hello World', TEST );
_ex( 'Post', 'verb', TEST );


esc_html__( 'Hello World', TEST );
esc_html_e( 'Hello World', TEST );
esc_html_x( 'Post', 'verb', TEST );


esc_attr__( 'Hello World', TEST );
esc_attr_e( 'Hello World', TEST );
esc_attr_x( 'Post', 'verb', TEST );


$apples = 4;
_n( '%d apple', '%d apples', $apples, TEST );
_nx( '%d post', '%d posts', $apples, 'noun, job positions', TEST );


_n_noop( '%d apple', '%d apples', TEST );
_nx_noop( '%d post', '%d posts', 'noun, job positions', TEST );
?>
```

With the previous fixture it works. 

But with the next one, it will works too:

```php
<?php

define( 'TEST2', 'my-domain' );

__( 'Hello World', TEST );
_x( 'Post', 'verb', TEST );
_e( 'Hello World', TEST );
_ex( 'Post', 'verb', TEST );


esc_html__( 'Hello World', TEST );
esc_html_e( 'Hello World', TEST );
esc_html_x( 'Post', 'verb', TEST );


esc_attr__( 'Hello World', TEST );
esc_attr_e( 'Hello World', TEST );
esc_attr_x( 'Post', 'verb', TEST );


$apples = 4;
_n( '%d apple', '%d apples', $apples, TEST );
_nx( '%d post', '%d posts', $apples, 'noun, job positions', TEST );


_n_noop( '%d apple', '%d apples', TEST );
_nx_noop( '%d post', '%d posts', 'noun, job positions', TEST );
?>
```

I mean, I set a constant with a value `TEST2` and the next lines use the value `TEST`.

By the other hand if I use this fixture, it fails:

```php
<?php

define( 'TEST', 'my-domain' );

__( 'Hello World', TEST2 );
_x( 'Post', 'verb', TEST );
_e( 'Hello World', TEST );
_ex( 'Post', 'verb', TEST );


esc_html__( 'Hello World', TEST );
esc_html_e( 'Hello World', TEST );
esc_html_x( 'Post', 'verb', TEST );


esc_attr__( 'Hello World', TEST );
esc_attr_e( 'Hello World', TEST );
esc_attr_x( 'Post', 'verb', TEST );


$apples = 4;
_n( '%d apple', '%d apples', $apples, TEST );
_nx( '%d post', '%d posts', $apples, 'noun, job positions', TEST );


_n_noop( '%d apple', '%d apples', TEST );
_nx_noop( '%d post', '%d posts', 'noun, job positions', TEST );
?>
```

Does the test should fail too with the second fixture?

**Comment by ichiriac** [comment]
Hi Felix,

As you can see [here](https://github.com/ichiriac/gulp-checktextdomain/blob/e926153311786c4eee2b191c3df7a279d58738b5/index.js#L169) the constant name is used exactly as a text.

So as you said in your text the domain "TEST" should pass. From the test engine, `__( 'Hello World', TEST );` is exactly the same as `__( 'Hello World', 'TEST' );`, so first and second pass and the `define` or `const` statements are not checked in case of keywords (that's OK as the define statement could be in another definition file).

The third test fails as `TEST2` domain is not allowed. If you want to handle more complex things like extracting defines statements, the problem can became hard to solve because you may have to solve dynamic expressions like : `define('my_domain', 'FOO' . 'BAR')` or `__('foo', my_domain . 'BAR')`.

You could do an improvement if you can dinstinguish allowed constants and allowed texts, with a sort of syntax :

```
    var options = {
      force: true,
      text_domain: ['my-domain', '$MY_DOMAIN'],
      create_report_file: true,
      keywords: keywords
    };
```
and a valid fixture could be 
```
__('Foo', 'my-domain');
__('Foo', MY_DOMAIN);
```
And an invalid fixture 
```
__('Foo', 'MY_DOMAIN');
```

**Comment by felixzapata** [comment]
hi @ichiriac , it is true.  Sorry I forgotten the options object so when I asked you about the test I did not put the correct value for the  `text_domain` option:
```javascript
    var options = {
      force: true,
      text_domain: 'TEST2',
      create_report_file: true,
      keywords: keywords
    };
```

Because PHP is not my everyday language nor WordPress, I want to be sure that this change fix perfectly with the [original issue](https://github.com/felixzapata/gulp-checktextdomain/issues/3).

I think that the correct fixture and, more clear, for this case is: (without the `define` line)

```php
<?php
__( 'Hello World', MY_CUSTOM_CONSTANT );
_x( 'Post', 'verb', MY_CUSTOM_CONSTANT );
_e( 'Hello World', MY_CUSTOM_CONSTANT );
_ex( 'Post', 'verb', MY_CUSTOM_CONSTANT );


esc_html__( 'Hello World', MY_CUSTOM_CONSTANT );
esc_html_e( 'Hello World', MY_CUSTOM_CONSTANT );
esc_html_x( 'Post', 'verb', MY_CUSTOM_CONSTANT );


esc_attr__( 'Hello World', MY_CUSTOM_CONSTANT );
esc_attr_e( 'Hello World', MY_CUSTOM_CONSTANT );
esc_attr_x( 'Post', 'verb', MY_CUSTOM_CONSTANT );


$apples = 4;
_n( '%d apple', '%d apples', $apples, MY_CUSTOM_CONSTANT );
_nx( '%d post', '%d posts', $apples, 'noun, job positions', MY_CUSTOM_CONSTANT );


_n_noop( '%d apple', '%d apples', MY_CUSTOM_CONSTANT );
_nx_noop( '%d post', '%d posts', 'noun, job positions', MY_CUSTOM_CONSTANT );
?>
```

And with these options:
```javascript
    var options = {
      force: true,
      text_domain: 'MY_CUSTOM_CONSTANT',
      create_report_file: true,
      keywords: keywords
    };
```

What do you think?

**Comment by ichiriac** [comment]
Agree with you, should pass

**Pull request merged**
